# Generated by Django 4.0 on 2023-01-13 01:09

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='solicitacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome_cliente', models.CharField(blank=True, db_column='nome_cliente', default=None, max_length=50, null=True)),
                ('cnpj', models.CharField(blank=True, db_column='cnpj', default=None, max_length=14, null=True)),
                ('valor_emprestimo', models.DecimalField(blank=True, db_column='valor_emprestimo', decimal_places=2, default=None, max_digits=10, null=True)),
                ('faturamento_ano', models.DecimalField(blank=True, db_column='faturamento_ano', decimal_places=2, default=None, max_digits=10, null=True)),
                ('nome_solicitante', models.CharField(blank=True, db_column='nome_solicitante', default=None, max_length=50, null=True)),
                ('cpf_solicitante', models.CharField(blank=True, db_column='cpf_solicitante', default=None, max_length=11, null=True)),
                ('telefone_solicitante', models.CharField(blank=True, db_column='telefone_solicitante', default=None, max_length=11, null=True)),
                ('email_solicitante', models.CharField(blank=True, db_column='email_solicitante', default=None, max_length=70, null=True)),
                ('data_solicitacao', models.DateTimeField(blank=True, db_column='data_solicitacao', default=datetime.datetime(2023, 1, 13, 1, 9, 56, 774421, tzinfo=utc), null=True)),
            ],
            options={
                'verbose_name': 'solicitacao',
                'verbose_name_plural': 'solicitacao',
                'db_table': 'solitacao',
                'managed': True,
            },
        ),
    ]
